# This is a basic workflow that is manually triggered

name: auto_Reserve

on:
  schedule:
    - cron: "0 13 * * *"  # 每天北京时间21:00启动（UTC 13:00）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: install dependency
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install build-essential libssl-dev libffi-dev python3-dev -y
          pip install cryptography requests opencv-python

      # - name: wait until 22:00 Beijing time
      #   run: |
      #     current_time=$(TZ='Asia/Shanghai' date +%s)
      #     target_time=$(TZ='Asia/Shanghai' date -d "22:00" +%s)
      #     wait_seconds=$(( target_time - current_time ))
      #     if [ $wait_seconds -gt 0 ]; then
      #       echo "Waiting for $wait_seconds seconds until 22:00"
      #       sleep $wait_seconds
      #     else
      #       echo "Already past 22:00, executing immediately."
      #     fi

      - name: run script in reserve mode
        env:
          USERNAMES: ${{ secrets.USERNAMES }}
          PASSWORDS: ${{ secrets.PASSWORDS }}
        run: |
          python main.py -m reserve --action
